// Generated by go-postgres-codegen 1
package persistence

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v4"
)

const OperatorsInsertSql = `
	INSERT INTO 
		public.operators
	(
		id,
		name
	)
	VALUES
		($1,$2)
`

const OperatorsUpdateSql = `
	UPDATE 
		public.operators
	SET
		id=$1,
		name=$2
	WHERE
		id=$3
`

const OperatorsDeleteSql = `
	DELETE FROM
		public.operators
	WHERE
		id=$1
`

type Operators struct {
	Id   int32  `db:"id"`
	Name string `db:"name"`
}

func (self *Operators) InsertTx(tx *pgx.Tx) (int64, error) {
	commandTag, err := (*tx).Exec(context.Background(), OperatorsInsertSql,
		self.Id,
		self.Name,
	)

	return commandTag.RowsAffected(), err
}

func BatchInsertOperators(tx *pgx.Tx, batch *[]Operators) (int64, error) {
	vals := []interface{}{}
	stmt := `
	INSERT INTO 
		public.operators
	(
		id,
		name
	)
	VALUES `
	c := 0
	for i, item := range *batch {
		stmt = stmt + fmt.Sprintf(`($%d,$%d)`, c+1, c+2)
		if i < len(*batch)-1 {
			stmt = stmt + ","
		}
		vals = append(vals, item.Id, item.Name)
		c = c + 2
	}

	commandTag, err := (*tx).Exec(context.Background(), stmt, vals...)

	return commandTag.RowsAffected(), err
}

func StrBatchInsertOperators(batchSize int) string {
	stmt := `
	INSERT INTO 
		public.operators
	(
		id,
		name
	)
	VALUES `
	c := 0
	for i := 0; i < batchSize; i++ {
		stmt = stmt + fmt.Sprintf(`($%d,$%d)`, c+1, c+2)
		if i < batchSize-1 {
			stmt = stmt + ","
		}
		c = c + 2
	}
	return stmt
}

func (self *Operators) UpdateTx(tx *pgx.Tx) (int64, error) {
	commandTag, err := (*tx).Exec(context.Background(), OperatorsUpdateSql,
		self.Id,
		self.Name,
		self.Id,
	)

	return commandTag.RowsAffected(), err
}

func (self *Operators) DeleteTx(tx *pgx.Tx) (int64, error) {
	commandTag, err := (*tx).Exec(context.Background(), OperatorsDeleteSql, self.Id)

	return commandTag.RowsAffected(), err
}

func (self *Operators) Scan(rows *pgx.Rows, extensions ...PersistenceExtension) {
	vals, _ := (*rows).Values()
	for i, f := range (*rows).FieldDescriptions() {
		val := vals[i]
		switch string(f.Name) {
		case "id":
			self.Id = val.(int32)
		case "name":
			self.Name = val.(string)
		default:
			for _, extension := range extensions {
				extension.Extend(string(f.Name), val)
			}
		}
	}
}
