// Generated by go-postgres-codegen 1
package persistence

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v4"
)

const UsersInsertSql = `
	INSERT INTO 
		public.users
	(
		id,
		email,
		name
	)
	VALUES
		($1,$2,$3)
`

const UsersUpdateSql = `
	UPDATE 
		public.users
	SET
		id=$1,
		email=$2,
		name=$3
	WHERE
		id=$4
`

const UsersDeleteSql = `
	DELETE FROM
		public.users
	WHERE
		id=$1
`

type Users struct {
	Id    string `db:"id"`
	Email string `db:"email"`
	Name  string `db:"name"`
}

func (self *Users) InsertTx(tx *pgx.Tx) (int64, error) {
	commandTag, err := (*tx).Exec(context.Background(), UsersInsertSql,
		self.Id,
		self.Email,
		self.Name,
	)

	return commandTag.RowsAffected(), err
}

func BatchInsertUsers(tx *pgx.Tx, batch *[]Users) (int64, error) {
	vals := []interface{}{}
	stmt := `
	INSERT INTO 
		public.users
	(
		id,
		email,
		name
	)
	VALUES `
	c := 0
	for i, item := range *batch {
		stmt = stmt + fmt.Sprintf(`($%d,$%d,$%d)`, c+1, c+2, c+3)
		if i < len(*batch)-1 {
			stmt = stmt + ","
		}
		vals = append(vals, item.Id, item.Email, item.Name)
		c = c + 3
	}

	commandTag, err := (*tx).Exec(context.Background(), stmt, vals...)

	return commandTag.RowsAffected(), err
}

func StrBatchInsertUsers(batchSize int) string {
	stmt := `
	INSERT INTO 
		public.users
	(
		id,
		email,
		name
	)
	VALUES `
	c := 0
	for i := 0; i < batchSize; i++ {
		stmt = stmt + fmt.Sprintf(`($%d,$%d,$%d)`, c+1, c+2, c+3)
		if i < batchSize-1 {
			stmt = stmt + ","
		}
		c = c + 3
	}
	return stmt
}

func (self *Users) UpdateTx(tx *pgx.Tx) (int64, error) {
	commandTag, err := (*tx).Exec(context.Background(), UsersUpdateSql,
		self.Id,
		self.Email,
		self.Name,
		self.Id,
	)

	return commandTag.RowsAffected(), err
}

func (self *Users) DeleteTx(tx *pgx.Tx) (int64, error) {
	commandTag, err := (*tx).Exec(context.Background(), UsersDeleteSql, self.Id)

	return commandTag.RowsAffected(), err
}

func (self *Users) Scan(rows *pgx.Rows, extensions ...PersistenceExtension) {
	vals, _ := (*rows).Values()
	for i, f := range (*rows).FieldDescriptions() {
		val := vals[i]
		switch string(f.Name) {
		case "id":
			self.Id = val.(string)
		case "email":
			self.Email = val.(string)
		case "name":
			self.Name = val.(string)
		default:
			for _, extension := range extensions {
				extension.Extend(string(f.Name), val)
			}
		}
	}
}
